### ISSUE TITLE
Request with no callback results in error

### ISSUE THREAD

**Issue by JacobReynolds** [godaddy/kubernetes-client#189]
The following request will cause an error, because there is no callback defined:
```javascript
const Api = require('kubernetes-client');
const core = new Api.Core(Api.config.getInCluster());
core.namespaces(process.env.POD_NAMESPACE).pod(process.env.POD_NAME).patch({
  body: {
    metadata: {
      labels: {
        app: 'working'
      }
    }
  }
})
```
```javascript
/usr/src/app/node_modules/kubernetes-client/lib/base.js:15
    cb(null, result.body);
    ^

TypeError: cb is not a function
    at /usr/src/app/node_modules/kubernetes-client/lib/base.js:15:5
    at Request.request [as _callback] (/usr/src/app/node_modules/kubernetes-client/lib/request.js:65:7)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Would it be possible to just add a check [here](https://github.com/godaddy/kubernetes-client/blob/f8f1d356244055b6bdebe5587c3142d5f69f3ceb/lib/base.js#L15) to see if a callback exists?

**Comment by silasbw** [comment]
Thanks @JacobReynolds.  I implemented support in https://github.com/godaddy/kubernetes-client/pull/193.  It should get merged and published with a new major version in a couple of days.
