### ISSUE TITLE
Unhandled promise rejection when IAM endpoint times out

### ISSUE THREAD

**Issue by ajpauwels** [godaddy/kubernetes-client#264]
Using the latest version of `kubernetes-client` with nodejs v9.8.0.

Frequently, my IAM endpoint will time out when I'm sending many parallel requests at once. This is obviously a failure of the endpoint, but I think there's an issue with how `kubernetes-client` handles those errors as well, as I can't seem to be able to catch them. This the code which handles the requests:

```
		try {
			switch (kubernetesVersion) {
			case '1.7':
				deploymentJSON.apiVersion = 'apps/v1beta1';
				result = await client.apis.apps.v1beta1.namespaces(namespace).deployments(deploymentJSON.metadata.name)
					.patch({headers: {'content-type': 'application/merge-patch+json'}, body: deploymentJSON});
				break;
			case '1.8':
				deploymentJSON.apiVersion = 'apps/v1beta2';
				result = await client.apis.apps.v1beta2.namespaces(namespace).deployments(deploymentJSON.metadata.name)
					.patch({headers: {'content-type': 'application/merge-patch+json'}, body: deploymentJSON});
				break;
			case '1.9':
				deploymentJSON.apiVersion = 'apps/v1';
				result = await client.apis.apps.v1.namespaces(namespace).deployments(deploymentJSON.metadata.name)
					.patch({headers: {'content-type': 'application/merge-patch+json'}, body: deploymentJSON});
				break;
			default:
				return callback(new Error(`Unrecognized Kubernetes version: ${kubernetesVersion}`));
			}
		} catch (err) {
			return callback(err);
		}

		return callback(null, result);
```

As you can see, this is pretty straightforward. When I get a 409 from Kubernetes, for example, I catch the error as expected, it bubbles up, and I report it.

However, when the IAM endpoint specified in my kubeconfig times out, this is what I get greeted with:
```
Unhandled rejection: {
  "message": "Request timed out",
  "stack": "RequestError: Request timed out\n    at timeoutFn (/home/alexandre/entryplan-admin/node_modules/openid-client/node_modules/got/index.js:319:53)\n    at asPromise (/home/alexandre/entryplan-admin/node_modules/openid-client/node_modules/got/index.js:397:18)\n    at got (/home/alexandre/entryplan-admin/node_modules/openid-client/node_modules/got/index.js:637:10)\n    at Function.got.(anonymous function) [as post] (/home/alexandre/entryplan-admin/node_modules/openid-client/node_modules/got/index.js:655:31)\n    at Object.post (/home/alexandre/entryplan-admin/node_modules/openid-client/lib/http.js:19:14)\n    at Promise.resolve.then (/home/alexandre/entryplan-admin/node_modules/openid-client/lib/client.js:758:32)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:118:7)",
  "name": "RequestError",
  "code": "ETIMEDOUT",
  "host": "iam.ng.bluemix.net",
  "hostname": "iam.ng.bluemix.net",
  "method": "POST",
  "path": "/kubernetes/token",
  "protocol": "https:",
  "url": "https://iam.ng.bluemix.net/kubernetes/token"
}
```

I'll try digging around the codebase to see if there's just a `try/catch` not getting used somewhere or something, but until then, figured I would see if anyone else has run into this.

**Comment by silasbw** [comment]
Thanks for reporting this.  I haven't had time to look into it, but still plan on doing so.

**Comment by ajpauwels** [comment]
As an update to this, I can confirm that this error occurs for any IAM endpoint failure, not just timeouts. 400 responses also result in an unhandled rejection.

**Comment by ajpauwels** [comment]
I've made a PR to fix this issue, it was a simple problem of not having a catch statement when calling `refreshAuth`:
https://github.com/godaddy/kubernetes-client/pull/324
