### ISSUE TITLE
ERR_TLS_CERT_ALTNAME_INVALID when connecting to Rancher cluster

### ISSUE THREAD

**Issue by spiffytech** [godaddy/kubernetes-client#274]
I have a Rancher 2.0 Kubernetes cluster that's accessible by IP address using its own generated certs. When I do any operations with kubernetes-client, I get this error:

```
(node:38728) UnhandledPromiseRejectionWarning: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 10.0.10.205 is not in the cert's list:
    at Object.checkServerIdentity (tls.js:229:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1065:27)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:635:8)
```

Is there an option to disable full SSL validation?

**Comment by silasbw** [comment]
Yes, you can use the `insecureSkipTlsVerify` option.

E.g.,

```js
new Client({ url: ..., insecureSkipTlsVerify: true })
```
