### ISSUE TITLE
Using ...pods.exec.post() results in Error: Upgrade request required

### ISSUE THREAD

**Issue by fefl** [godaddy/kubernetes-client#319]
I am currently trying to use `client.api.v1.namespaces(ns).pods(pod).exec.post()` to run a command in a pod. Using it looks something like this:
```
const cmd = await client.api.v1.namespaces(ns).pods(pod).exec.post({ qs: { command: ['nginx', '-s', 'reload'] } });
```

This results in the following error:
```
{ Error: Upgrade request required
    at http.request (/app/node_modules/fluent-openapi/lib/loader.js:230:25)
    at Request.request [as _callback] (/app/node_modules/kubernetes-client/lib/request.js:107:14)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19) code: 400, statusCode: 400 }
```

This error occurs with Kubernetes v1.9.0 as well as with v1.9.4 and v1.9.5. I used version 6.0.0 of your client.

If there is any more information I can provide you to help me solve this just tell me.

**Comment by silasbw** [comment]
kubernetes-client doesn't `exec`, but it would be nice if it did.  it's been on the TODO list for a long time.

This issue discussing how to use `exec` in node.js might be helpful to you: https://github.com/godaddy/kubernetes-client/issues/19

**Comment by gempesaw** [comment]
Oh, this reminds me, I sussed out how the Kube API wants to talk over the websocket channel for the seemingly undocumented exec endpoint. It wants websocket frames where the first byte indicates the stream (stdout/stderr/....something else/out of band-errors) and then the command is the rest of the frame as binary.

I'm happy to open a PR for it, but I don't know what kind of interface `kubernetes-client` would like to present around the functionality. Like - when you call `exec`, it returns a websocket connection that you can pass commands to? or just these one-off "execute a command and get a string result back"? Also, I believe it'd require an additional websocket library dependency, if that's a concern...

**Comment by gempesaw** [comment]
Cool, that sounds like an entirely reasonable first step. I hope to take a look this weekend :)

**Comment by gempesaw** [comment]
@silasbw hey, where would you expect this functionality to live? if i'm understanding the structure correctly, I'd guess it it belongs in fluent-openapi... as special logic in the [post function](https://github.com/silasbw/fluent-openapi/blob/175fa4cb370b122967ba58cf36cf147c26ac4f50/lib/loader.js#L284-L293)? 

I don't think I can express it as part of a swagger spec - last I checked swagger didn't have built in support for websockets...

**Comment by silasbw** [comment]
What if we add code here-ish and handle it in a way similar to 401ing:

https://github.com/godaddy/kubernetes-client/blob/master/lib/request.js#L94

If the response has an upgrade header, we upgrade the connection and retry.  We might be able to handle that way without adding endpoint specific logic.
