### ISSUE TITLE
Struggling to read pods

### ISSUE THREAD

**Issue by Stono** [godaddy/kubernetes-client#467]
Hi, 
New to this library, so forgive me if this is a stupid question - but I cannot for the life of me get a list of pods in a namespace.

This really simple example:
```
const Client = require('kubernetes-client').Client
const config = require('kubernetes-client').config
const client = new Client({ config: config.getInCluster(), version: '1.13' })

const func = async function bacon() {
  try {
  await client.loadSpec()
  console.log(await client.apis.v1.namespaces('istio-system'));
  } catch(ex) {
   console.log(ex);
  }
}

func();
```

Gives me:
```
TypeError: Cannot read property 'namespaces' of undefined
    at bacon (/usr/local/autotrader/app/test.js:8:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Stono** [comment]
Closing, user error - it should have been `  console.log(await client.api.v1.namespaces('istio-system').pods.get());`
