### ISSUE TITLE
Not able to authenticate to EKS with custom path to config file on Lambda

### ISSUE THREAD

**Issue by ameymehta** [godaddy/kubernetes-client#491]
Hi, I am not able to authenticate with custom path config file. I am running the code on Lambda

Code for client construction is
`const Request = require('kubernetes-client/backends/request');
const backend = new Request(Request.config.fromKubeconfig('/tmp/config.yaml'));
const client = new Client({ backend, version: '1.11' });`

Error is

`Error: Failed to run cmd.
    at Promise (/opt/nodejs/node_modules/kubernetes-client/lib/auth-providers/cmd.js:44:23)
    at new Promise (<anonymous>)
    at Object.refresh (/opt/nodejs/node_modules/kubernetes-client/lib/auth-providers/cmd.js:30:12)
    at Promise (/opt/nodejs/node_modules/kubernetes-client/backends/request/client.js:17:14)
    at new Promise (<anonymous>)
    at refreshAuth (/opt/nodejs/node_modules/kubernetes-client/backends/request/client.js:15:10)
    at Request.request [as _callback] (/opt/nodejs/node_modules/kubernetes-client/backends/request/client.js:136:16)
    at Request.self.callback (/opt/nodejs/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)`

**Comment by tminussi** [comment]
I have just raised the same issue. #490
