### ISSUE TITLE
Deprecation notices when using typescript as documented

### ISSUE THREAD

**Issue by nesl247** [godaddy/kubernetes-client#529]
When using typescript as documented in the README, the following deprecation notices occur:

```
kubernetes-client deprecated require('kubernetes-client').config, use require('kubernetes-client/backends/request').config. at ../../libraries/waitForJob.ts:17:67

kubernetes-client deprecated fromKubeconfig see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md#request-kubeconfig- at ../../libraries/waitForJob.ts:17:74

kubernetes-client deprecated Client({ config }), see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at ../../libraries/waitForJob.ts:17:28

 kubernetes-client deprecated Request() without a .kubeconfig option, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at ../../node_modules/kubernetes-client/lib/swagger-client.js:200:19

```

Am I doing something wrong, or was the typescript support not updated with regards to the deprecations?

**Comment by zoidbergwill** [comment]
I think the examples need to be updated too?
