### ISSUE TITLE
Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by b1zzu** [godaddy/kubernetes-client#549]
#### What have I done

```js
const Client = require("kubernetes-client").Client;
const client = new Client({ version: "1.13" });
```
#### What is the result

```
    TypeError: Cannot read property 'request' of undefined
      at new Request (node_modules/kubernetes-client/lib/backends/request.js:100:35)
      at new Client (node_modules/kubernetes-client/lib/swagger-client.js:132:40)
      at Function.<anonymous> (util/openshift.ts:23:20)
      at step (util/openshift.ts:33:23)
      at Object.next (util/openshift.ts:14:53)
      at /home/dbizzarr/Projects/github.com/aerogear/test-suite/backup/util/openshift.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (util/openshift.ts:4:12)
      at Function.OpenshiftHelper.new (util/openshift.ts:46:16)
      at Suite.<anonymous> (test/backup_and_restore.ts:43:41)
      at step (test/backup_and_restore.ts:33:23)
      at Object.next (test/backup_and_restore.ts:14:53)
      at /home/dbizzarr/Projects/github.com/aerogear/test-suite/backup/test/backup_and_restore.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (test/backup_and_restore.ts:4:12)
      at Context.<anonymous> (test/backup_and_restore.ts:40:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
```

#### Additional informations
 
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0+724e12f93f", GitCommit:"d5465d715197862b15c8cf05e864d7c3cfea6917", GitTreeState:"clean", BuildDate:"2019-10-10T22:03:41Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-10T17:49:11Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by b1zzu** [comment]
I was using an old version
